pandemic_cpu: .FORCE
	g++ Pandemic_Clean/Pandemic_Clean_unix.cpp Pandemic_Clean/PandemicSim.cpp Pandemic_Clean/Person.cpp Pandemic_Clean/Location.cpp Pandemic_Clean/LocationArray.cpp Pandemic_Clean/DailyLocationArray.cpp Pandemic_Clean/debug.cpp Pandemic_Clean/stdafx.cpp Pandemic_Clean/resource_polling_unix.cpp -o pandemic_cpu -fopenmp
	
.FORCE:
	
